# --- СЛОВАРЬ ПЕРЕВОДОВ ИНТЕРФЕЙСА (9 ЯЗЫКОВ) ---
TRANSLATIONS = {
    "RU": {
        "title": "Гид по безопасности и вкусу",
        "sidebar_title": "Настройки туриста",
        "lang_select": "Язык / Language",
        "allergens_title": "На что у вас аллергия?",
        "tab_menu": "🍽 Блюда",
        "tab_places": "📍 Места и Рестораны",
        "tab_passport": "🆘 Паспорт",
        "tab_sos": "🚑 SOS",
        "menu_title": "Декодер Меню",
        "menu_subtitle": "Безопасные национальные блюда",
        "places_title": "Каталог Мест",
        "places_subtitle": "Лучшие рестораны, природа и памятники",
        "safe": "✅ Безопасно",
        "dangerous": "⛔ ОПАСНО! Содержит:",
        "tip": "Совет гида:",
        "passport_title": "Цифровой переводчик",
        "passport_desc": "Покажите этот экран официанту или врачу.",
        "passport_warning": "У меня сильная аллергия!",
        "sos_title": "Экстренная помощь",
        "sos_btn": "🏥 Ближайшая АПТЕКА (2GIS)",
        "police_btn": "👮 Ближайшая ПОЛИЦИЯ (2GIS)",
        "call_ambulance": "Скорая",
        "call_police": "Полиция",
        "types": {"Food": "Рестораны/Еда", "Safety": "Культура/Памятники", "Danger": "Природа/Активный отдых"},
        "nutrition_title": "Пищевая ценность (на 100г)",
        "prot": "Белки",
        "fats": "Жиры",
        "carbs": "Углев.",
        "open_2gis": "Открыть в 2GIS ➔",
        "map_filter": "Фильтр категорий",
        # WELCOME PAGE
        "welcome_title": "Добро пожаловать в Шымкент!",
        "welcome_subtitle": "Перед началом установите эти важные приложения:",
        "app_2gis_desc": "Карты, автобусы и справочник. Работает без интернета (если скачать город).",
        "app_yandex_desc": "Главное такси в городе. Быстро и надежно.",
        "btn_start": "✅ Готово, начать путешествие!"
    },
    "EN": {
        "title": "Safety & Taste Guide",
        "sidebar_title": "Tourist Settings",
        "lang_select": "Language",
        "allergens_title": "Your Allergies?",
        "tab_menu": "🍽 Dishes",
        "tab_places": "📍 Places & Food",
        "tab_passport": "🆘 Passport",
        "tab_sos": "🚑 SOS",
        "menu_title": "Menu Decoder",
        "menu_subtitle": "Safe national dishes",
        "places_title": "Places Catalog",
        "places_subtitle": "Top restaurants, nature and monuments",
        "safe": "✅ Safe for you",
        "dangerous": "⛔ DANGER! Contains:",
        "tip": "Guide tip:",
        "passport_title": "Digital Translator",
        "passport_desc": "Show this screen to a waiter or doctor.",
        "passport_warning": "I have a severe allergy!",
        "sos_title": "Emergency Help",
        "sos_btn": "🏥 Nearest PHARMACY (2GIS)",
        "police_btn": "👮 Nearest POLICE (2GIS)",
        "call_ambulance": "Ambulance",
        "call_police": "Police",
        "types": {"Food": "Restaurants/Food", "Safety": "Culture/Monuments", "Danger": "Nature/Active"},
        "nutrition_title": "Nutrition Facts (per 100g)",
        "prot": "Protein",
        "fats": "Fat",
        "carbs": "Carbs",
        "open_2gis": "Open in 2GIS ➔",
        "map_filter": "Category Filter",
        # WELCOME PAGE
        "welcome_title": "Welcome to Shymkent!",
        "welcome_subtitle": "Please install these essential apps first:",
        "app_2gis_desc": "Maps, bus routes, and directory. Works offline (if city downloaded).",
        "app_yandex_desc": "The main taxi app. Fast and reliable (like Uber).",
        "btn_start": "✅ Done, let's start!"
    },
    "KZ": {
        "title": "Қауіпсіздік және Дәм гиді",
        "sidebar_title": "Турист баптаулары",
        "lang_select": "Тіл / Language",
        "allergens_title": "Сізде неге аллергия бар?",
        "tab_menu": "🍽 Тағамдар",
        "tab_places": "📍 Орындар",
        "tab_passport": "🆘 Паспорт",
        "tab_sos": "🚑 SOS",
        "menu_title": "Мәзір Декодері",
        "menu_subtitle": "Қауіпсіз ұлттық тағамдар",
        "places_title": "Орындар Каталогы",
        "places_subtitle": "Үздік мейрамханалар, табиғат және ескерткіштер",
        "safe": "✅ Қауіпсіз",
        "dangerous": "⛔ ҚАУІПТІ! Құрамында:",
        "tip": "Гид кеңесі:",
        "passport_title": "Сандық аудармаш",
        "passport_desc": "Бұл экранды даяшыға көрсетіңіз.",
        "passport_warning": "Менде қатты аллергия бар!",
        "sos_title": "Шұғыл көмек",
        "sos_btn": "🏥 Жақын ДӘРІХАНА (2GIS)",
        "police_btn": "👮 Жақын ПОЛИЦИЯ (2GIS)",
        "call_ambulance": "Жедел жәрдем",
        "call_police": "Полиция",
        "types": {"Food": "Тағам", "Safety": "Мәдениет/Ескерткіштер", "Danger": "Табиғат/Белсенді демалыс"},
        "nutrition_title": "Тағамдық құндылығы (100г)",
        "prot": "Ақуыз",
        "fats": "Майлар",
        "carbs": "Көмірсу",
        "open_2gis": "2GIS арқылы ашу ➔",
        "map_filter": "Санат сүзгісі",
        # WELCOME PAGE
        "welcome_title": "Шымкентке қош келдіңіз!",
        "welcome_subtitle": "Саяхат алдында осы қосымшаларды жүктеп алыңыз:",
        "app_2gis_desc": "Карталар, автобустар және анықтамалық. Офлайн жұмыс істейді.",
        "app_yandex_desc": "Қаладағы басты такси қызметі. Жылдам және ыңғайлы.",
        "btn_start": "✅ Дайын, бастайық!"
    },
    "CN": {
        "title": "安全与美食指南",
        "sidebar_title": "游客设置",
        "lang_select": "语言",
        "allergens_title": "您对什么过敏？",
        "tab_menu": "🍽 菜单解码器",
        "tab_places": "📍 地点",
        "tab_passport": "🆘 护照",
        "tab_sos": "🚑 紧急",
        "menu_title": "菜单解码器",
        "menu_subtitle": "安全的民族菜肴",
        "places_title": "地点目录",
        "places_subtitle": "顶级餐厅和安全区",
        "safe": "✅ 安全",
        "dangerous": "⛔ 危险！包含：",
        "tip": "提示：",
        "passport_title": "数字翻译",
        "passport_desc": "请向服务员出示此屏幕。",
        "passport_warning": "我有严重的过敏症！",
        "sos_title": "紧急求助",
        "sos_btn": "🏥 最近的药房 (2GIS)",
        "police_btn": "👮 最近的警察局 (2GIS)",
        "call_ambulance": "救护车",
        "call_police": "警察",
        "types": {"Food": "食物", "Safety": "安全点", "Danger": "危险区"},
        "nutrition_title": "营养成分 (100克)",
        "prot": "蛋白质",
        "fats": "脂肪",
        "carbs": "碳水",
        "open_2gis": "在 2GIS 中打开 ➔",
        "map_filter": "类别筛选",
        # WELCOME PAGE
        "welcome_title": "欢迎来到奇姆肯特！",
        "welcome_subtitle": "请先安装这些必备应用程序：",
        "app_2gis_desc": "地图、公交路线和指南。离线可用。",
        "app_yandex_desc": "主要的出租车应用。快速可靠。",
        "btn_start": "✅ 完成，开始吧！"
    },
    "TR": {
        "title": "Güvenlik ve Lezzet Rehberi",
        "sidebar_title": "Turist Ayarları",
        "lang_select": "Dil",
        "allergens_title": "Neye alerjiniz var?",
        "tab_menu": "🍽 Menü Rehberi",
        "tab_places": "📍 Yerler",
        "tab_passport": "🆘 Pasaport",
        "tab_sos": "🚑 Acil",
        "menu_title": "Menü Kod Çözücü",
        "menu_subtitle": "Güvenli yerel yemekler",
        "places_title": "Mekan Kataloğu",
        "places_subtitle": "En iyi restoranlar ve güvenli bölgeler",
        "safe": "✅ Güvenli",
        "dangerous": "⛔ TEHLİKE! İçerir:",
        "tip": "İpucu:",
        "passport_title": "Dijital Çevirmen",
        "passport_desc": "Bu ekranı garsona gösterin.",
        "passport_warning": "Şiddetli alerjim var!",
        "sos_title": "Acil Yardım",
        "sos_btn": "🏥 En yakın ECZANE (2GIS)",
        "police_btn": "👮 En yakın POLİS (2GIS)",
        "call_ambulance": "Ambulans",
        "call_police": "Polis",
        "types": {"Food": "Yemek", "Safety": "Güvenlik", "Danger": "Risk Bölgesi"},
        "nutrition_title": "Besin Değerleri (100g)",
        "prot": "Protein",
        "fats": "Yağ",
        "carbs": "Karbonh.",
        "open_2gis": "2GIS'te aç ➔",
        "map_filter": "Kategori Filtresi",
        # WELCOME PAGE
        "welcome_title": "Çimkent'e Hoşgeldiniz!",
        "welcome_subtitle": "Lütfen önce bu önemli uygulamaları yükleyin:",
        "app_2gis_desc": "Haritalar, otobüsler ve rehber. Çevrimdışı çalışır.",
        "app_yandex_desc": "Ana taksi uygulaması. Hızlı ve güvenilir.",
        "btn_start": "✅ Tamam, başlayalım!"
    },
    "FR": {
        "title": "Guide de Sécurité et Goût",
        "sidebar_title": "Paramètres",
        "lang_select": "Langue",
        "allergens_title": "Vos allergies?",
        "tab_menu": "🍽 Menu",
        "tab_places": "📍 Lieux",
        "tab_passport": "🆘 Passeport",
        "tab_sos": "🚑 SOS",
        "menu_title": "Décodeur de Menu",
        "menu_subtitle": "Plats nationaux sûrs",
        "places_title": "Catalogue des lieux",
        "places_subtitle": "Meilleurs restaurants et zones sûres",
        "safe": "✅ Sûr",
        "dangerous": "⛔ DANGER! Contient:",
        "tip": "Conseil:",
        "passport_title": "Traducteur Numérique",
        "passport_desc": "Montrez cet écran au serveur.",
        "passport_warning": "J'ai une allergie grave!",
        "sos_title": "Aide d'urgence",
        "sos_btn": "🏥 PHARMACIE la plus proche (2GIS)",
        "police_btn": "👮 POLICE la plus proche (2GIS)",
        "call_ambulance": "Ambulance",
        "call_police": "Police",
        "types": {"Food": "Nourriture", "Safety": "Sécurité", "Danger": "Zone à risque"},
        "nutrition_title": "Valeurs nutritionnelles (100g)",
        "prot": "Protéines",
        "fats": "Lipides",
        "carbs": "Glucides",
        "open_2gis": "Ouvrir dans 2GIS ➔",
        "map_filter": "Filtre de catégorie",
        # WELCOME PAGE
        "welcome_title": "Bienvenue à Shymkent !",
        "welcome_subtitle": "Veuillez d'abord installer ces applications essentielles :",
        "app_2gis_desc": "Cartes, bus et annuaire. Fonctionne hors ligne.",
        "app_yandex_desc": "La principale application de taxi. Rapide et fiable.",
        "btn_start": "✅ C'est fait, commençons !"
    },
    "DE": {
        "title": "Sicherheits- & Geschmacksführer",
        "sidebar_title": "Einstellungen",
        "lang_select": "Sprache",
        "allergens_title": "Worauf sind Sie allergisch?",
        "tab_menu": "🍽 Menü",
        "tab_places": "📍 Orte",
        "tab_passport": "🆘 Ausweis",
        "tab_sos": "🚑 SOS",
        "menu_title": "Menü-Decoder",
        "menu_subtitle": "Sichere nationale Gerichte",
        "places_title": "Ortskatalog",
        "places_subtitle": "Top-Restaurants und sichere Zonen",
        "safe": "✅ Sicher",
        "dangerous": "⛔ GEFAHR! Enthält:",
        "tip": "Guide-Tipp:",
        "passport_title": "Digitaler Übersetzer",
        "passport_desc": "Zeigen Sie dies dem Kellner.",
        "passport_warning": "Ich habe eine schwere Allergie!",
        "sos_title": "Notfallhilfe",
        "sos_btn": "🏥 Nächste APOTHEKE (2GIS)",
        "police_btn": "👮 Nächste POLIZEI (2GIS)",
        "call_ambulance": "Krankenwagen",
        "call_police": "Polizei",
        "types": {"Food": "Essen", "Safety": "Sicherheit", "Danger": "Gefahr"},
        "nutrition_title": "Nährwerte (100g)",
        "prot": "Eiweiß",
        "fats": "Fett",
        "carbs": "Kohlenh.",
        "open_2gis": "In 2GIS öffnen ➔",
        "map_filter": "Kategoriefilter",
        # WELCOME PAGE
        "welcome_title": "Willkommen in Shymkent!",
        "welcome_subtitle": "Bitte installieren Sie zuerst diese wichtigen Apps:",
        "app_2gis_desc": "Karten, Busse und Verzeichnis. Funktioniert offline.",
        "app_yandex_desc": "Die wichtigste Taxi-App. Schnell und zuverlässig.",
        "btn_start": "✅ Erledigt, los geht's!"
    },
    "ES": {
        "title": "Guía de Seguridad y Sabor",
        "sidebar_title": "Configuración",
        "lang_select": "Idioma",
        "allergens_title": "¿A qué eres alérgico?",
        "tab_menu": "🍽 Menú",
        "tab_places": "📍 Lugares",
        "tab_passport": "🆘 Pasaporte",
        "tab_sos": "🚑 SOS",
        "menu_title": "Decodificador de Menú",
        "menu_subtitle": "Platos nacionales seguros",
        "places_title": "Catálogo de Lugares",
        "places_subtitle": "Mejores restaurantes y zonas seguras",
        "safe": "✅ Seguro",
        "dangerous": "⛔ PELIGRO! Contiene:",
        "tip": "Consejo:",
        "passport_title": "Traductor Digital",
        "passport_desc": "Muestre esto al camarero.",
        "passport_warning": "¡Tengo una alergia grave!",
        "sos_title": "Ayuda de Emergencia",
        "sos_btn": "🏥 FARMACIA cercana (2GIS)",
        "police_btn": "👮 POLICÍA cercana (2GIS)",
        "call_ambulance": "Ambulancia",
        "call_police": "Policía",
        "types": {"Food": "Comida", "Safety": "Seguridad", "Danger": "Peligro"},
        "nutrition_title": "Valor nutricional (100g)",
        "prot": "Proteínas",
        "fats": "Grasas",
        "carbs": "Carbohid.",
        "open_2gis": "Abrir en 2GIS ➔",
        "map_filter": "Filtro de categoría",
        # WELCOME PAGE
        "welcome_title": "¡Bienvenido a Shymkent!",
        "welcome_subtitle": "Instale estas aplicaciones esenciales primero:",
        "app_2gis_desc": "Mapas, autobuses y directorio. Funciona sin conexión.",
        "app_yandex_desc": "La principal aplicación de taxi. Rápida y fiable.",
        "btn_start": "✅ ¡Hecho, empecemos!"
    },
    "AR": {
        "title": "دليل السلامة والذوق",
        "sidebar_title": "الإعدادات",
        "lang_select": "لغة",
        "allergens_title": "هل لديك حساسية؟",
        "tab_menu": "🍽 القائمة",
        "tab_places": "📍 أماكن",
        "tab_passport": "🆘 جواز سفر",
        "tab_sos": "🚑 طوارئ",
        "menu_title": "مترجم القائمة",
        "menu_subtitle": "أطباق وطنية آمنة",
        "places_title": "كتالوج الأماكن",
        "places_subtitle": "أفضل المطاعم والمناطق الآمنة",
        "safe": "✅ آمن",
        "dangerous": "⛔ خطر! يحتوي على:",
        "tip": "نصيحة:",
        "passport_title": "مترجم رقمي",
        "passport_desc": "أظهر هذا للنادل.",
        "passport_warning": "لدي حساسية شديدة!",
        "sos_title": "مساعدة الطوارئ",
        "sos_btn": "🏥 أقرب صيدلية (2GIS)",
        "police_btn": "👮 أقرب شرطة (2GIS)",
        "call_ambulance": "إسعاف",
        "call_police": "شرطة",
        "types": {"Food": "طعام", "Safety": "أمان", "Danger": "خطر"},
        "nutrition_title": "القيمة الغذائية (100 غرام)",
        "prot": "بروتين",
        "fats": "دهون",
        "carbs": "كربوهيدرات",
        "open_2gis": "افتح في 2GIS ➔",
        "map_filter": "تصفية الفئات",
        # WELCOME PAGE
        "welcome_title": "مرحبًا بك في شيمكنت!",
        "welcome_subtitle": "يرجى تثبيت هذه التطبيقات الأساسية أولاً:",
        "app_2gis_desc": "الخرائط والحافلات والدليل. يعمل بدون انترنت.",
        "app_yandex_desc": "تطبيق التاكسي الرئيسي. سريع وموثوق.",
        "btn_start": "✅ تم، لنبدأ!"
    }
}

# --- СЛОВАРЬ АЛЛЕРГЕНОВ ---
ALLERGEN_TRANSLATIONS = {
    "Gluten": {"RU": "Глютен (Мука)", "EN": "Gluten", "KZ": "Глютен", "CN": "麸质", "TR": "Glüten", "FR": "Gluten", "DE": "Gluten", "ES": "Gluten", "AR": "الغلوتين"},
    "Lactose": {"RU": "Лактоза (Молоко)", "EN": "Lactose", "KZ": "Лактоза", "CN": "乳糖", "TR": "Laktoz", "FR": "Lactose", "DE": "Laktose", "ES": "Lactosa", "AR": "اللاكتوز"},
    "Nuts": {"RU": "Орехи", "EN": "Nuts", "KZ": "Жаңғақтар", "CN": "坚果", "TR": "Kuruyemiş", "FR": "Noix", "DE": "Nüsse", "ES": "Nueces", "AR": "مكسرات"},
    "Meat": {"RU": "Мясо", "EN": "Meat", "KZ": "Ет", "CN": "肉", "TR": "Et", "FR": "Viande", "DE": "Fleisch", "ES": "Carne", "AR": "لحم"},
    "Salt": {"RU": "Соль (Высокое содержание)", "EN": "Salt", "KZ": "Тұз", "CN": "盐", "TR": "Tuz", "FR": "Sel", "DE": "Salz", "ES": "Sal", "AR": "ملح"},
    "Sugar": {"RU": "Сахар", "EN": "Sugar", "KZ": "Қант", "CN": "糖", "TR": "Şeker", "FR": "Sucre", "DE": "Zucker", "ES": "Azúcar", "AR": "سكر"},
    "Oil": {"RU": "Жир/Масло", "EN": "Oil/Fat", "KZ": "Май", "CN": "油", "TR": "Yağ", "FR": "Huile", "DE": "Öl/Fett", "ES": "Aceite/Grasa", "AR": "زيت/دهون"},
    "Onion": {"RU": "Лук", "EN": "Onion", "KZ": "Пияз", "CN": "洋葱", "TR": "Soğan", "FR": "Oignon", "DE": "Zwiebel", "ES": "Cebolla", "AR": "بصل"},
    "Fish": {"RU": "Рыба", "EN": "Fish", "KZ": "Балық", "CN": "鱼", "TR": "Balık", "FR": "Poisson", "DE": "Fisch", "ES": "Pescado", "AR": "سمك"}
}

# --- БАЗА БЛЮД ---
DISHES = [
    {
        "id": 1,
        "name": {"RU": "Бешбармак", "EN": "Beshbarmak", "KZ": "Бесбармақ"},
        "desc": {"RU": "Праздничное блюдо: отварное мясо с домашней лапшой и луком.", "EN": "Festive dish: boiled meat with homemade noodles and onion.", "KZ": "Ет пен қамырдан жасалған ұлттық тағам."},
        "allergens": ["Gluten", "Meat", "Onion", "Salt"],
        "safety_score": 4,
        "safety_tip": {"RU": "Очень сытное и жирное. Запивайте сорпой.", "EN": "Very rich and fatty. Drink broth with it."},
        "nutrition": {"kcal": 280, "protein": 16, "fat": 12, "carbs": 24},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/%D0%91%D0%B5%D1%88%D0%B1%D0%B0%D1%80%D0%BC%D0%B0%D0%BA_%D0%B8%D0%B7_%D0%B3%D0%BE%D0%B2%D1%8F%D0%B4%D0%B8%D0%BD%D1%8B_01.jpg/2560px-%D0%91%D0%B5%D1%88%D0%B1%D0%B0%D1%80%D0%BC%D0%B0%D0%BA_%D0%B8%D0%B7_%D0%B3%D0%BE%D0%B2%D1%8F%D0%B4%D0%B8%D0%BD%D1%8B_01.jpg"
    },
    {
        "id": 2,
        "name": {"RU": "Куырдак", "EN": "Kuyrdak", "KZ": "Қуырдақ"},
        "desc": {"RU": "Жаркое из свежих субпродуктов (печень, сердце) и мяса.", "EN": "Roast of fresh offal (liver, heart) and meat.", "KZ": "Өкпе-бауырдан жасалған қуырма."},
        "allergens": ["Meat", "Onion", "Oil"],
        "safety_score": 4,
        "safety_tip": {"RU": "Может быть тяжелым для непривычного желудка.", "EN": "Can be heavy for digestion."},
        "nutrition": {"kcal": 220, "protein": 18, "fat": 15, "carbs": 4},
        "image": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Kazakh_quwyrdaq.jpg"
    },
    {
        "id": 3,
        "name": {"RU": "Казы", "EN": "Kazy", "KZ": "Қазы"},
        "desc": {"RU": "Конина в виде копчёно-вяленой колбасы, деликатес.", "EN": "Horse meat sausage, smoked and dried delicacy.", "KZ": "Жылқы етінен жасалған шұжық."},
        "allergens": ["Meat", "Salt"],
        "safety_score": 5,
        "safety_tip": {"RU": "Высококалорийный деликатес. Ешьте умеренно.", "EN": "High calorie delicacy. Eat moderately."},
        "nutrition": {"kcal": 450, "protein": 18, "fat": 40, "carbs": 1},
        "image": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Horsemeat_platter.jpg"
    },
    {
        "id": 4,
        "name": {"RU": "Баурсак", "EN": "Baursak", "KZ": "Бауырсақ"},
        "desc": {"RU": "Жареные кусочки теста, подаются к чаю.", "EN": "Fried dough pieces, served with tea.", "KZ": "Майға қуырылған нан."},
        "allergens": ["Gluten", "Oil"],
        "safety_score": 5,
        "safety_tip": {"RU": "Жареное в масле. Вкусно, но калорийно.", "EN": "Fried in oil. Tasty but caloric."},
        "nutrition": {"kcal": 350, "protein": 8, "fat": 10, "carbs": 55},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Boortsog.JPG/1280px-Boortsog.JPG"
    },
    {
        "id": 5,
        "name": {"RU": "Кумыс", "EN": "Kumys", "KZ": "Қымыз"},
        "desc": {"RU": "Ферментированное кобылье молоко.", "EN": "Fermented mare's milk.", "KZ": "Бие сүтінен ашытылған сусын."},
        "allergens": ["Lactose"],
        "safety_score": 3,
        "safety_tip": {"RU": "Специфический вкус. Начинайте с малых порций (100мл).", "EN": "Specific taste. Start with small portions."},
        "nutrition": {"kcal": 50, "protein": 2, "fat": 1.5, "carbs": 5},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Kumys-bottle.jpg/960px-Kumys-bottle.jpg"
    },
    {
        "id": 6,
        "name": {"RU": "Шубат", "EN": "Shubat", "KZ": "Шұбат"},
        "desc": {"RU": "Ферментированное верблюжье молоко (гуще кумыса).", "EN": "Fermented camel's milk (thicker than kumys).", "KZ": "Түйе сүтінен ашытылған сусын."},
        "allergens": ["Lactose"],
        "safety_score": 3,
        "safety_tip": {"RU": "Очень жирный напиток. Осторожно, если слабый желудок.", "EN": "Very rich. Caution if you have sensitive stomach."},
        "nutrition": {"kcal": 80, "protein": 4, "fat": 5, "carbs": 5},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Shubat.jpg/1280px-Shubat.jpg"
    },
    {
        "id": 7,
        "name": {"RU": "Курт", "EN": "Kurt", "KZ": "Құрт"},
        "desc": {"RU": "Сухие солёные шарики из кислого молока.", "EN": "Dry salty balls made of sour milk.", "KZ": "Кептірілген сүзбе шариктері."},
        "allergens": ["Lactose", "Salt"],
        "safety_score": 5,
        "safety_tip": {"RU": "Очень соленый. Полезен в жару, но осторожно гипертоникам.", "EN": "Very salty. Good in heat, careful with blood pressure."},
        "nutrition": {"kcal": 260, "protein": 50, "fat": 15, "carbs": 12},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Mercado_de_Chorsu_03.jpg/2560px-Mercado_de_Chorsu_03.jpg"
    },
    {
        "id": 8,
        "name": {"RU": "Жент", "EN": "Zhent", "KZ": "Жент"},
        "desc": {"RU": "Сладкая масса из жареного проса, масла, меда и орехов.", "EN": "Sweet mass of fried millet, butter, honey and nuts.", "KZ": "Талқан, май, қант қосылған тәтті."},
        "allergens": ["Lactose", "Sugar", "Nuts", "Gluten"],
        "safety_score": 5,
        "safety_tip": {"RU": "Очень сытный и сладкий десерт.", "EN": "Very filling and sweet dessert."},
        "nutrition": {"kcal": 400, "protein": 8, "fat": 20, "carbs": 50},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Zhent_2.jpg/1280px-Zhent_2.jpg"
    },
    {
        "id": 9,
        "name": {"RU": "Шелпек", "EN": "Shelpek", "KZ": "Шелпек"},
        "desc": {"RU": "Тонкая лепешка, жареная в масле.", "EN": "Thin flatbread fried in oil.", "KZ": "Майға пісірілген жұқа нан."},
        "allergens": ["Gluten", "Oil"],
        "safety_score": 5,
        "safety_tip": {"RU": "Традиционно пекут по пятницам. Жирное блюдо.", "EN": "Traditionally baked on Fridays. Oily."},
        "nutrition": {"kcal": 300, "protein": 7, "fat": 10, "carbs": 45},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/ShelpekKZ1.JPG/1280px-ShelpekKZ1.JPG"
    },
    {
        "id": 10,
        "name": {"RU": "Тандыр нан", "EN": "Tandyr Nan", "KZ": "Тандыр нан"},
        "desc": {"RU": "Хлеб, запеченный в глиняной печи (тандыре).", "EN": "Bread baked in a clay oven (tandoor).", "KZ": "Тандырда піскен нан."},
        "allergens": ["Gluten"],
        "safety_score": 5,
        "safety_tip": {"RU": "Всегда берите горячим! Безопасно.", "EN": "Always buy hot! Safe."},
        "nutrition": {"kcal": 250, "protein": 8, "fat": 1, "carbs": 50},
        "image": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Taj_Lepeshki.jpg"
    },
    {
        "id": 11,
        "name": {"RU": "Плов", "EN": "Plov", "KZ": "Палау"},
        "desc": {"RU": "Рис с мясом, морковью и специями.", "EN": "Rice with meat, carrots and spices.", "KZ": "Күріш, ет, сәбіз қосылған тағам."},
        "allergens": ["Meat", "Oil", "Onion"],
        "safety_score": 4,
        "safety_tip": {"RU": "В Шымкенте плов жирный. Ешьте с салатом Ачичук.", "EN": "Shymkent plov is oily. Eat with tomato salad."},
        "nutrition": {"kcal": 360, "protein": 10, "fat": 15, "carbs": 45},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Polu.jpg/2560px-Polu.jpg"
    },
    {
        "id": 12,
        "name": {"RU": "Самса", "EN": "Samsa", "KZ": "Самса"},
        "desc": {"RU": "Слоеная выпечка с рубленым мясом из тандыра.", "EN": "Puff pastry with chopped meat from tandoor.", "KZ": "Тандырда піскен етті бәліш."},
        "allergens": ["Gluten", "Meat", "Onion", "Oil"],
        "safety_score": 4,
        "safety_tip": {"RU": "Осторожно, внутри горячий бульон!", "EN": "Caution, hot broth inside!"},
        "nutrition": {"kcal": 300, "protein": 10, "fat": 15, "carbs": 30},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Ouzb%C3%A9kistan-Samsas.jpg/960px-Ouzb%C3%A9kistan-Samsas.jpg"
    },
    {
        "id": 13,
        "name": {"RU": "Манты", "EN": "Manty", "KZ": "Мәнті"},
        "desc": {"RU": "Большие паровые пельмени с мясом и луком.", "EN": "Large steamed dumplings with meat and onions.", "KZ": "Буға піскен қамыр тағам."},
        "allergens": ["Gluten", "Meat", "Onion"],
        "safety_score": 5,
        "safety_tip": {"RU": "Едят руками. Безопасно, так как на пару.", "EN": "Eaten by hands. Safe (steamed)."},
        "nutrition": {"kcal": 240, "protein": 10, "fat": 10, "carbs": 25},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Manti_as_a_fast_food_dish_in_Germany.JPG/1280px-Manti_as_a_fast_food_dish_in_Germany.JPG"
    },
    {
        "id": 14,
        "name": {"RU": "Лагман", "EN": "Lagman", "KZ": "Лағман"},
        "desc": {"RU": "Длинная вытяжная лапша с густым мясным соусом и овощами.", "EN": "Pulled noodles with thick meat sauce and vegetables.", "KZ": "Созылмалы кеспе."},
        "allergens": ["Gluten", "Meat", "Onion", "Oil"],
        "safety_score": 4,
        "safety_tip": {"RU": "Может быть острым. Уточняйте степень остроты.", "EN": "Can be spicy. Ask about spice level."},
        "nutrition": {"kcal": 200, "protein": 7, "fat": 8, "carbs": 25},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/%D0%9F%D0%BE%D1%80%D1%86%D0%B8%D1%8F_%D0%BB%D0%B0%D0%B3%D0%BC%D0%B0%D0%BD%D0%B0.jpg/2560px-%D0%9F%D0%BE%D1%80%D1%86%D0%B8%D1%8F_%D0%BB%D0%B0%D0%B3%D0%BC%D0%B0%D0%BD%D0%B0.jpg"
    },
    {
        "id": 15,
        "name": {"RU": "Коктал", "EN": "Koktal", "KZ": "Көктал"},
        "desc": {"RU": "Крупная рыба, запеченная с овощами (горячее копчение).", "EN": "Large fish baked/smoked with vegetables.", "KZ": "Көкөніспен пісірілген балық."},
        "allergens": ["Fish", "Onion"],
        "safety_score": 4,
        "safety_tip": {"RU": "Внимательно следите за костями.", "EN": "Watch out for fish bones."},
        "nutrition": {"kcal": 150, "protein": 18, "fat": 8, "carbs": 0},
        "image": "https://images.mir24.tv/sZ_CZPWhZt1inzAz5ZajI5qlVQAsGFuHaTUtij2Zz6w/q:95/w:1166/h:696/c:1279:752:nowe:-17:0/rt:fill-down/czM6Ly9taXIyNC10di9tZWRpYS9BcnRpY2xlL2ltYWdlLzA3Njk5YWJiLTg2NzctNTMxMC1iNzEwLWJkNDlkMjFmN2Y4Ni9mMzU3NDFjYWUyODA0ZWExOGE4MDViMDY4Njg3NDY4YjllNDNiM2MxODY4YTFmMDMxZDc0NTc2ZThjZDUwNjI4LmpwZw.jpg"
    },
    {
        "id": 16,
        "name": {"RU": "Наурыз-коже", "EN": "Nauryz Kozhe", "KZ": "Наурыз көже"},
        "desc": {"RU": "Праздничный суп из 7 ингредиентов (мясо, злаки, молоко).", "EN": "Festive soup of 7 ingredients (meat, grains, milk).", "KZ": "7 түрлі дәмнен жасалған көже."},
        "allergens": ["Lactose", "Gluten", "Meat", "Salt"],
        "safety_score": 5,
        "safety_tip": {"RU": "Символ изобилия. Очень сытно.", "EN": "Symbol of abundance. Very filling."},
        "nutrition": {"kcal": 120, "protein": 6, "fat": 4, "carbs": 15},
        "image": "https://resizer.mail.ru/p/0ad121a9-815b-5581-a68d-54271046a6e1/AQAF5tQmHoPCeeA2QCHXX7p_aELlbIxM7YCiugtctU3bSQn4Izv6ECWZ4cJal4cY-xA-16P5OCxtGhuE0ONfgkwLyVk.jpg"
    },
    {
        "id": 17,
        "name": {"RU": "Шашлык", "EN": "Shashlyk", "KZ": "Кәуәп"},
        "desc": {"RU": "Маринованное мясо, жареное на углях.", "EN": "Marinated meat grilled on skewers.", "KZ": "Шоққа піскен ет."},
        "allergens": ["Meat", "Onion", "Salt"],
        "safety_score": 4,
        "safety_tip": {"RU": "Проверяйте прожарку мяса.", "EN": "Check if meat is fully cooked."},
        "nutrition": {"kcal": 250, "protein": 20, "fat": 18, "carbs": 1},
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/%D0%A8%D0%B0%D1%88%D0%BB%D1%8B%D0%BA_25.05.2013.jpg/1280px-%D0%A8%D0%B0%D1%88%D0%BB%D1%8B%D0%BA_25.05.2013.jpg"
    },
    {
        "id": 18,
        "name": {"RU": "Сорпа", "EN": "Sorpa", "KZ": "Сорпа"},
        "desc": {"RU": "Насыщенный мясной бульон.", "EN": "Rich meat broth.", "KZ": "Ет сорпасы."},
        "allergens": ["Meat", "Salt", "Onion"],
        "safety_score": 5,
        "safety_tip": {"RU": "Отлично восстанавливает силы. Пейте горячим.", "EN": "Restores energy. Drink hot."},
        "nutrition": {"kcal": 60, "protein": 4, "fat": 4, "carbs": 1},
        "image": "https://perspectum.info/wp-content/uploads/2021/07/dreamstime_xxl_136677871-1024x645.jpg"
    },
    {
        "id": 19,
        "name": {"RU": "Балкаймак", "EN": "Balkaymak", "KZ": "Балқаймақ"},
        "desc": {"RU": "Сладкий десерт из томленых сливок с медом.", "EN": "Sweet dessert from stewed cream with honey.", "KZ": "Бал қосылған қаймақ."},
        "allergens": ["Lactose", "Sugar"],
        "safety_score": 4,
        "safety_tip": {"RU": "Очень сладко и жирно. Деликатес.", "EN": "Very sweet and rich."},
        "nutrition": {"kcal": 450, "protein": 2, "fat": 40, "carbs": 15},
        "image": "https://cdn.nur.kz/images/1200x675/2ffd282e52b42f18.jpeg?version=1"
    },
    {
        "id": 20,
        "name": {"RU": "Иримшик", "EN": "Irimshik", "KZ": "Ірімшік"},
        "desc": {"RU": "Твердый или мягкий сыр из молока, сладковатый.", "EN": "Hard or soft cheese, slightly sweet.", "KZ": "Сүттен жасалған тәтті өнім."},
        "allergens": ["Lactose", "Sugar"],
        "safety_score": 5,
        "safety_tip": {"RU": "Натуральный источник кальция. Безопасно для детей.", "EN": "Natural calcium source. Safe for kids."},
        "nutrition": {"kcal": 350, "protein": 15, "fat": 25, "carbs": 20},
        "image": "https://cdn.nur.kz/images/1200x675/5586cbb61a809a76.jpeg?version=1"
    }
]

# --- БАЗА ЛОКАЦИЙ ---
LOCATIONS = [
    # --- ГОРЫ И ПРИРОДА (Danger) ---
    {"name": {"RU": "Сайрам-Угамский Парк", "EN": "Sairam-Ugam Park"}, "type": "Danger", "desc": "⚠️ ГОРЫ! Нужна жесткая подошва.", "2gis_link": "https://2gis.kz/shymkent/search/Сайрам-Угамский"},
    {"name": {"RU": "Пустыня Аккум", "EN": "Akkum Desert"}, "type": "Danger", "desc": "☀️ ПУСТЫНЯ. Берите воду!", "2gis_link": "https://2gis.kz/shymkent/search/Аккум"},
    {"name": {"RU": "Келиншектау", "EN": "Kelinshek Tau"}, "type": "Danger", "desc": "🏔 ГОРЫ. Похоже на Италию.", "2gis_link": "https://2gis.kz/shymkent/search/Келиншектау"},
    {"name": {"RU": "Скалы Кырык Кыз", "EN": "Kyryk Kyz Rocks"}, "type": "Danger", "desc": "🏜 Песчаные скалы и легенды. Уникальное явление.", "2gis_link": "https://2gis.kz/kk/geo/70030076468486682"},
    {"name": {"RU": "Озеро Сусинген", "EN": "Lake Susingen"}, "type": "Danger", "desc": "🥾 Горное озеро (исчезает в июле). Поход 4 дня.", "2gis_link": "https://2gis.kz/geo/70030076464150628"},

    # --- КУЛЬТУРА И БЕЗОПАСНОСТЬ (Safety) ---
    {"name": {"RU": "Заповедник Аксу-Жабаглы", "EN": "Aksu-Zhabagly Reserve"}, "type": "Safety", "desc": "🛂 НУЖНО УДОСТОВЕРЕНИЕ. Водопад Каинды.", "2gis_link": "https://2gis.kz/geo/70030076439795379"},
    {"name": {"RU": "Мавзолей Х.А. Ясави", "EN": "Yasaui Mausoleum"}, "type": "Safety", "desc": "🕌 СВЯТЫНЯ. Дресс-код.", "2gis_link": "https://go.2gis.com/TAGK6"}, # ОБНОВЛЕНА ССЫЛКА
    {"name": {"RU": "Комплекс Караван-Сарай", "EN": "Karavan Saray"}, "type": "Safety", "desc": "Туристический комплекс / Tourist complex.", "2gis_link": "https://go.2gis.com/yc8GQ"},
    {"name": {"RU": "Библиотека Фараб", "EN": "Farab Library"}, "type": "Safety", "desc": "Современная библиотека / Modern library.", "2gis_link": "https://go.2gis.com/cAyTH"},
    {"name": {"RU": "Музей Ясави", "EN": "Yasawi Museum"}, "type": "Safety", "desc": "Исторический музей / Historical museum.", "2gis_link": "https://go.2gis.com/ayAYV"},
    {"name": {"RU": "Мавзолей Гаухар-ана", "EN": "Gauhar Ana Mausoleum"}, "type": "Safety", "desc": "Святое место / Holy place.", "2gis_link": "https://go.2gis.com/OKbgV"},
    {"name": {"RU": "Театр Алтын Самурык", "EN": "Altyn Samuryk Theatre"}, "type": "Safety", "desc": "Летающий театр / Flying theatre.", "2gis_link": "https://go.2gis.com/82hD9"},
    {"name": {"RU": "Музей Улы Дала Ели", "EN": "Great Steppe Museum"}, "type": "Safety", "desc": "Музей Великой Степи / Great Steppe Museum.", "2gis_link": "https://go.2gis.com/WubW8"},
    {"name": {"RU": "Поющий фонтан (Туркестан)", "EN": "Musical Fountain"}, "type": "Safety", "desc": "Шоу фонтанов / Fountain show.", "2gis_link": "https://go.2gis.com/vkhp8"},
    {"name": {"RU": "Мавзолей Есим-хана", "EN": "Esim Khan Mausoleum"}, "type": "Safety", "desc": "Исторический мавзолей.", "2gis_link": "https://go.2gis.com/Gb74f"},
    {"name": {"RU": "Мавзолей Тауке-хана", "EN": "Tauke Khan Mausoleum"}, "type": "Safety", "desc": "Исторический мавзолей.", "2gis_link": "https://go.2gis.com/llQEN"},
    {"name": {"RU": "Фотозона I Love Turkistan", "EN": "I Love Turkistan"}, "type": "Safety", "desc": "Фотозона / Photo spot.", "2gis_link": "https://go.2gis.com/PvDLU"},
    {"name": {"RU": "Ханская мечеть", "EN": "Khan Mosque"}, "type": "Safety", "desc": "Мечеть XVI-XVII вв.", "2gis_link": "https://go.2gis.com/ePFQM"},
    {"name": {"RU": "Шильдехана", "EN": "Shildekhana"}, "type": "Safety", "desc": "Исторический памятник.", "2gis_link": "https://go.2gis.com/j9Q76"},
    {"name": {"RU": "Великий Шелковый Путь (Туркестан)", "EN": "Silk Road (Turkestan)"}, "type": "Safety", "desc": "Декоративное сооружение.", "2gis_link": "https://go.2gis.com/RBpqy"},
    {"name": {"RU": "Монумент Славы (Туркестан)", "EN": "Glory Monument (Turkestan)"}, "type": "Safety", "desc": "В честь ВОВ.", "2gis_link": "https://go.2gis.com/tvEt7"},
    {"name": {"RU": "Памятник Назарбаеву", "EN": "Nazarbayev Monument"}, "type": "Safety", "desc": "Памятник первому президенту.", "2gis_link": "https://go.2gis.com/E8L3i"},
    {"name": {"RU": "Памятник Ибн Сине", "EN": "Ibn Sina Monument"}, "type": "Safety", "desc": "Великий целитель.", "2gis_link": "https://go.2gis.com/v2AzL"},
    {"name": {"RU": "Подземная мечеть Кумшик-ата", "EN": "Kumshik Ata Mosque"}, "type": "Safety", "desc": "Подземная мечеть.", "2gis_link": "https://go.2gis.com/XvYwE"},
    {"name": {"RU": "Мавзолей Арыстан-Баба", "EN": "Arystan Bab Mausoleum"}, "type": "Safety", "desc": "Святыня. Учитель Ясави.", "2gis_link": "https://go.2gis.com/Arm0R"},
    {"name": {"RU": "Памятник Абаю (Туркестан)", "EN": "Abay Monument"}, "type": "Safety", "desc": "Великий поэт.", "2gis_link": "https://go.2gis.com/nHbxf"},
    {"name": {"RU": "Памятник Абылай-хану", "EN": "Abylai Khan Monument"}, "type": "Safety", "desc": "Великий хан.", "2gis_link": "https://go.2gis.com/1rkJy"},
    {"name": {"RU": "Памятник Алатау Батыру", "EN": "Alatau Batyr Monument"}, "type": "Safety", "desc": "Батыр.", "2gis_link": "https://go.2gis.com/wkvyT"},
    {"name": {"RU": "Памятник Ш. Калдаякову (Туркестан)", "EN": "Shamshi Kaldayakov (Turkestan)"}, "type": "Safety", "desc": "Композитор.", "2gis_link": "https://go.2gis.com/ghi9U"},
    {"name": {"RU": "Памятник воинам-интернационалистам", "EN": "Internationalist Warriors"}, "type": "Safety", "desc": "Памятник.", "2gis_link": "https://go.2gis.com/VxCn4"},
    {"name": {"RU": "Мемориал Славы (Туркестан)", "EN": "Glory Memorial"}, "type": "Safety", "desc": "Мемориал.", "2gis_link": "https://go.2gis.com/l90B5"},
    {"name": {"RU": "Памятник Р. Есетову", "EN": "R. Esetov Monument"}, "type": "Safety", "desc": "Герой Советского Союза.", "2gis_link": "https://go.2gis.com/RmADB"},
    {"name": {"RU": "Старик и мальчик", "EN": "Old Man and Boy"}, "type": "Safety", "desc": "Скульптура.", "2gis_link": "https://go.2gis.com/FpI8u"},
    
    # --- ПРЕДЫДУЩИЕ ЛОКАЦИИ (ШЫМКЕНТ И ОКРЕСТНОСТИ) ---
    {"name": {"RU": "Мавзолей Домалак Ана", "EN": "Domalak Ana Mausoleum"}, "type": "Safety", "desc": "Святое место.", "2gis_link": "https://2gis.kz/shymkent/search/Домалак%20Ана"},
    {"name": {"RU": "Пещера Акмешит", "EN": "Akmeshit Cave"}, "type": "Safety", "desc": "Уникальная пещера.", "2gis_link": "https://2gis.kz/shymkent/search/Пещера%20Акмешит"},
    {"name": {"RU": "Водопад Туттыбулак", "EN": "Tuttybulak Waterfall"}, "type": "Safety", "desc": "Живописная природа.", "2gis_link": "https://2gis.kz/shymkent/search/Туттыбулак"},
    {"name": {"RU": "Колодец Укаш Ата", "EN": "Ukash Ata Well"}, "type": "Safety", "desc": "Священный колодец.", "2gis_link": "https://2gis.kz/shymkent/search/Укаш%20Ата"},
    {"name": {"RU": "Мавзолей Ибрагим Ата", "EN": "Ibrahim Ata Mausoleum"}, "type": "Safety", "desc": "Сайрам. Культурный объект.", "2gis_link": "https://2gis.kz/shymkent/search/Ибрагим%20Ата"},
    {"name": {"RU": "Мавзолей Карашаш Ана", "EN": "Karashash Ana Mausoleum"}, "type": "Safety", "desc": "Сайрам.", "2gis_link": "https://2gis.kz/shymkent/search/Карашаш%20Ана"},
    {"name": {"RU": "Гора Казыгурт", "EN": "Kazygurt Mountain"}, "type": "Safety", "desc": "Легенда о Ноевом Ковчеге.", "2gis_link": "https://2gis.kz/shymkent/search/Казыгурт"},
    {"name": {"RU": "Памятник Турмахану", "EN": "Orynbayuly Turmakhan"}, "type": "Safety", "desc": "Культурное наследие.", "2gis_link": "https://go.2gis.com/jusnZ"},
    {"name": {"RU": "550-летие Ханства", "EN": "550 Years of Khanate"}, "type": "Safety", "desc": "Исторический монумент.", "2gis_link": "https://go.2gis.com/1Nmr3"},
    {"name": {"RU": "Памятник Ш. Калдаякову (Шымкент)", "EN": "Shamshi Kaldayakov (Shymkent)"}, "type": "Safety", "desc": "Король казахского вальса.", "2gis_link": "https://go.2gis.com/3z0O2"},
    {"name": {"RU": "Памятник Б. Момышулы", "EN": "B. Momyshuly Monument"}, "type": "Safety", "desc": "Герой ВОВ.", "2gis_link": "https://go.2gis.com/qh2u0"},
    {"name": {"RU": "Алтын Шанырак", "EN": "Altyn Shanyrak"}, "type": "Safety", "desc": "Символ единства.", "2gis_link": "https://go.2gis.com/vuzq5"},
    {"name": {"RU": "Фонтан Независимости", "EN": "Independence Fountain"}, "type": "Safety", "desc": "Центральный парк.", "2gis_link": "https://go.2gis.com/Z5oU7"},
    {"name": {"RU": "Мавзолей Ботбай Ата", "EN": "Botbay Ata Mausoleum"}, "type": "Safety", "desc": "Святое место.", "2gis_link": "https://go.2gis.com/RmLJm"},
    {"name": {"RU": "Памятник Ш. Уалиханову", "EN": "Sh. Walikhanov Monument"}, "type": "Safety", "desc": "Великий ученый.", "2gis_link": "https://go.2gis.com/gKIaJ"},
    {"name": {"RU": "Обелиск Славы (ВОВ)", "EN": "Glory Obelisk (WWII)"}, "type": "Safety", "desc": "Вечный огонь.", "2gis_link": "https://go.2gis.com/1tSIO"},
    {"name": {"RU": "Бюст Гани Иляева", "EN": "Gani Ilyaev Bust"}, "type": "Safety", "desc": "Известный художник.", "2gis_link": "https://go.2gis.com/R2M02"},
    {"name": {"RU": "Бюст Алии Молдагуловой", "EN": "Aliya Moldagulova Bust"}, "type": "Safety", "desc": "Герой ВОВ.", "2gis_link": "https://go.2gis.com/8yXYJ"},
    {"name": {"RU": "Паровоз (Музей)", "EN": "Steam Train"}, "type": "Safety", "desc": "ЖД вокзал.", "2gis_link": "https://go.2gis.com/IKVea"},
    {"name": {"RU": "Шелковый Путь (Шымкент)", "EN": "Silk Road (Shymkent)"}, "type": "Safety", "desc": "Исторический символ.", "2gis_link": "https://go.2gis.com/t9mck"},
    {"name": {"RU": "Памятник Ветеранам", "EN": "Nuclear Test Veterans"}, "type": "Safety", "desc": "Семипалатинский полигон.", "2gis_link": "https://go.2gis.com/qmQNL"},

    # --- РЕСТОРАНЫ (Food) ---
    {"name": {"RU": "Shejire", "EN": "Shejire"}, "type": "Food", "desc": "Популярный ресторан / Popular restaurant.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001102685530"},
    {"name": {"RU": "Sham", "EN": "Sham"}, "type": "Food", "desc": "Атмосферное место / Atmospheric place.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001090430628"},
    {"name": {"RU": "Каусар", "EN": "Kausar"}, "type": "Food", "desc": "Восточная кухня / Oriental cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001064497850"},
    {"name": {"RU": "Шардара №1 Балык", "EN": "Shardara Fish"}, "type": "Food", "desc": "Рыбные блюда / Fish dishes.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001096954434"},
    {"name": {"RU": "Address", "EN": "Address"}, "type": "Food", "desc": "Ресторан / Restaurant.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001105151320"},
    {"name": {"RU": "Villa Delle Rose", "EN": "Villa Delle Rose"}, "type": "Food", "desc": "Итальянская кухня / Italian cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001100637541"},
    {"name": {"RU": "Tәтті Grill", "EN": "Tatti Grill"}, "type": "Food", "desc": "Гриль меню / Grill menu.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001104967005"},
    {"name": {"RU": "Мариям", "EN": "Mariyam"}, "type": "Food", "desc": "Уютное кафе / Cozy cafe.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001104381768"},
    {"name": {"RU": "Murager", "EN": "Murager"}, "type": "Food", "desc": "Национальная кухня / National cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001026019634"},
    {"name": {"RU": "Асем", "EN": "Asem"}, "type": "Food", "desc": "Традиционные блюда / Traditional dishes.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001099667132"},
    {"name": {"RU": "Восточный рай", "EN": "Eastern Paradise"}, "type": "Food", "desc": "Восточная кухня / Oriental cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001069504118"},
    {"name": {"RU": "Pinta pub", "EN": "Pinta pub"}, "type": "Food", "desc": "Паб и напитки / Pub & drinks.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001025934316"},
    {"name": {"RU": "Каусар (Филиал)", "EN": "Kausar (Branch)"}, "type": "Food", "desc": "Тандырная кухня / Tandoor cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001098240960"},
    {"name": {"RU": "Kymyz Mix", "EN": "Kymyz Mix"}, "type": "Food", "desc": "Напитки из кумыса / Kumys drinks.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001097014007"},
    {"name": {"RU": "Grand beshbarmak", "EN": "Grand beshbarmak"}, "type": "Food", "desc": "Лучший бешбармак / Best beshbarmak.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001105438637"},
    {"name": {"RU": "Al Hayr halal food", "EN": "Al Hayr"}, "type": "Food", "desc": "Халяль еда / Halal food.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001089703915"},
    {"name": {"RU": "Urbo coffee", "EN": "Urbo coffee"}, "type": "Food", "desc": "Кофейня / Coffee shop.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001103047734"},
    {"name": {"RU": "Бархан Burger Shop", "EN": "Barkhan Burger"}, "type": "Food", "desc": "Бургеры / Burgers.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001075782429"},
    {"name": {"RU": "Saba", "EN": "Saba"}, "type": "Food", "desc": "Семейный ресторан / Family restaurant.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001104142975"},
    {"name": {"RU": "Тумар", "EN": "Tumar"}, "type": "Food", "desc": "Ресторан / Restaurant.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001093827284"},
    {"name": {"RU": "Monterra", "EN": "Monterra"}, "type": "Food", "desc": "Изысканная кухня / Fine dining.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001105777401"},
    {"name": {"RU": "ПОНТОС", "EN": "PONTOS"}, "type": "Food", "desc": "Греческая кухня / Greek cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001025796084"},
    {"name": {"RU": "Мизам", "EN": "Mizam"}, "type": "Food", "desc": "Банкетный зал / Banquet hall.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001035308808"},
    {"name": {"RU": "Эштай Ата", "EN": "Eshtay Ata"}, "type": "Food", "desc": "Традиционная кухня / Traditional cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001095753837"},
    {"name": {"RU": "The one", "EN": "The one"}, "type": "Food", "desc": "Лаунж бар / Lounge bar.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001105895755"},
    {"name": {"RU": "KIM CHI", "EN": "KIM CHI"}, "type": "Food", "desc": "Корейская кухня / Korean cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001030160764"},
    {"name": {"RU": "Kazakhasia", "EN": "Kazakhasia"}, "type": "Food", "desc": "Азиатский фьюжн / Asian fusion.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001025715751"},
    {"name": {"RU": "Aurum Family", "EN": "Aurum Family"}, "type": "Food", "desc": "Семейный ресторан / Family restaurant.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001082501473"},
    {"name": {"RU": "Salt", "EN": "Salt"}, "type": "Food", "desc": "Мясной ресторан / Steakhouse.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001104580872"},
    {"name": {"RU": "Qazashka", "EN": "Qazashka"}, "type": "Food", "desc": "Национальный колорит / National vibes.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001065646113"},
    {"name": {"RU": "WOK WOK", "EN": "WOK WOK"}, "type": "Food", "desc": "Паназиатская кухня / Pan-Asian cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001082040963"},
    {"name": {"RU": "Vavilon", "EN": "Vavilon"}, "type": "Food", "desc": "Развлекательный комплекс / Entertainment complex.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001094459608"},
    {"name": {"RU": "Kidspark", "EN": "Kidspark"}, "type": "Food", "desc": "Детское кафе / Kids cafe.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001084247543"},
    {"name": {"RU": "Procoffee", "EN": "Procoffee"}, "type": "Food", "desc": "Кофе и десерты / Coffee & desserts.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001104178794"},
    {"name": {"RU": "Grand Golden Hills", "EN": "Grand Golden Hills"}, "type": "Food", "desc": "Ресторан / Restaurant.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001101389784"},
    {"name": {"RU": "Nomad Burgers", "EN": "Nomad Burgers"}, "type": "Food", "desc": "Бургерная / Burger joint.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001103399715"},
    {"name": {"RU": "Grand Giza", "EN": "Grand Giza"}, "type": "Food", "desc": "Ресторан / Restaurant.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001098961142"},
    {"name": {"RU": "COFFEETERIA", "EN": "COFFEETERIA"}, "type": "Food", "desc": "Кофейня / Coffee house.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001100226819"},
    {"name": {"RU": "Физули", "EN": "Fizuli"}, "type": "Food", "desc": "Шашлычная / Kebab house.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001026016313"},
    {"name": {"RU": "Erzhan Plov", "EN": "Erzhan Plov"}, "type": "Food", "desc": "Пловный центр / Plov center.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001098487148"},
    {"name": {"RU": "Master Burger", "EN": "Master Burger"}, "type": "Food", "desc": "Фастфуд / Fast food.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001067604253"},
    {"name": {"RU": "Ясин", "EN": "Yasin"}, "type": "Food", "desc": "Халяль кафе / Halal cafe.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001095461035"},
    {"name": {"RU": "ЭльДоШа", "EN": "ElDoSha"}, "type": "Food", "desc": "Донер кебаб / Doner kebab.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001025886007"},
    {"name": {"RU": "Төрт қазан", "EN": "Tort Kazan"}, "type": "Food", "desc": "Национальная кухня / National cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001100095945"},
    {"name": {"RU": "Dadiani", "EN": "Dadiani"}, "type": "Food", "desc": "Грузинская кухня / Georgian cuisine.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001065727880"},
    {"name": {"RU": "Жеті тандыр", "EN": "Zheti Tandyr"}, "type": "Food", "desc": "Самса и лепешки / Samsa & bread.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001039517343"},
    {"name": {"RU": "BEVERLY", "EN": "BEVERLY"}, "type": "Food", "desc": "Кафе / Cafe.", "2gis_link": "https://2gis.kz/shymkent/geo/70000001029456516"}
]